# Generated by Django 5.0.6 on 2024-05-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_done',
            field=models.BooleanField(default=False),
        ),
    ]
